[package]
name = "rm-viewer"
version.workspace = true
edition.workspace = true

[lib]
name = "rm_viewer"

[[bin]]
name = "remote-mac-viewer"
path = "src/main.rs"

[dependencies]
rm-protocol = { path = "../rm-protocol" }
rm-client = { path = "../rm-client" }
rm-relay = { path = "../rm-relay" }
rm-decode = { path = "../rm-decode" }
moonlight-sys = { path = "../moonlight-sys" }
rm-gamestream = { path = "../rm-gamestream" }
serde_json.workspace = true
rustybuzz = "0.20"
ab_glyph_rasterizer = "0.1"

[target.'cfg(windows)'.dependencies.windows]
version = "0.61"
features = [
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
  "Win32_System_LibraryLoader",
  "Win32_UI_HiDpi",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_WindowsAndMessaging",
  "Win32_Storage_Xps",
  "Win32_Storage_EnhancedStorage",
  "Win32_System_Com",
  "Win32_System_Com_StructuredStorage",
  "Win32_System_DataExchange",
  "Win32_System_Memory",
  "Win32_System_Variant",
  "Win32_UI_Shell",
  "Win32_UI_Shell_PropertiesSystem",
  "Win32_Graphics_Direct3D",
  "Win32_Graphics_Direct3D_Fxc",
  "Win32_Graphics_Direct3D11",
  "Win32_Graphics_Dxgi",
  "Win32_Graphics_Dxgi_Common",
  "Win32_UI_Controls",
  "Win32_Graphics_Dwm",
  "Win32_Graphics_DirectComposition",
  "Win32_Media",
  "Win32_Media_MediaFoundation",
  "Win32_Media_Audio",
  "Win32_Security",
  "Win32_System_Registry",
  "Win32_System_Console",
  "Win32_System_Threading",
]

[dev-dependencies]
rm-fakeagent = { path = "../rm-fakeagent" }
openh264 = "0.9"
