[package]
name = "rm-fakeagent"
version.workspace = true
edition.workspace = true

[lib]
name = "rm_fakeagent"

[[bin]]
name = "rm-fakeagent"
path = "src/main.rs"

[dependencies]
serde_json.workspace = true
rm-protocol = { path = "../rm-protocol" }
rm-relay = { path = "../rm-relay" }
openh264 = "0.9"
